/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2024-08-05 04:27:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webcontent.birt.pages.parameter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.eclipse.birt.report.utility.ParameterAccessor;
import org.eclipse.birt.report.context.BaseAttributeBean;
import org.eclipse.birt.report.context.ScalarParameterBean;
import org.eclipse.birt.report.service.api.ParameterDefinition;

public final class TextBoxParameterFragment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.eclipse.birt.report.utility.ParameterAccessor");
    _jspx_imports_classes.add("org.eclipse.birt.report.context.BaseAttributeBean");
    _jspx_imports_classes.add("org.eclipse.birt.report.context.ScalarParameterBean");
    _jspx_imports_classes.add("org.eclipse.birt.report.service.api.ParameterDefinition");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 0, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      org.eclipse.birt.report.context.BaseAttributeBean attributeBean = null;
      attributeBean = (org.eclipse.birt.report.context.BaseAttributeBean) _jspx_page_context.getAttribute("attributeBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (attributeBean == null){
        throw new java.lang.InstantiationException("bean attributeBean not found within scope");
      }
      out.write('\n');
      out.write('\n');
      out.write('\n');

	ScalarParameterBean parameterBean = ( ScalarParameterBean ) attributeBean.getParameterBean( );
	String encodedParameterName = ParameterAccessor.htmlEncode( parameterBean.getName( ) );

      out.write("\n");
      out.write("<TR>\n");
      out.write("	<TD NOWRAP>\n");
      //out.write("		<IMG class=\"icon_parameter\" SRC=\"birt/images/Parameter.png\" ALT=\"");
      out.print( parameterBean.getDisplayName( ) );
      out.write("\" TITLE=\"");
      out.print( parameterBean.getToolTip( ) );
      out.write("\"/>\n");
      out.write("	</TD>\n");
      out.write("	<TD NOWRAP>\n");
      out.write("		<SPAN TITLE=\"");
      out.print( parameterBean.getToolTip( ) );
      out.write("\"><LABEL FOR=\"");
      out.print( encodedParameterName );
      out.write('"');
      out.write('>');
      out.print( parameterBean.getDisplayName( ) );
      out.write(":</LABEL></SPAN>\n");
      out.write("		");
      out.write('\n');
      out.write('	');
      out.write('	');

		if ( parameterBean.isRequired( ) )
		{
		
      out.write("\n");
      out.write("			<SPAN style=\"color:red;\"><LABEL FOR=\"");
      out.print( encodedParameterName );
      out.write("\">*</LABEL></SPAN>\n");
      out.write("		");

		}
		
      out.write("\n");
      out.write("	</TD>\n");
      out.write("</TR>\n");
      out.write("<TR>\n");
      out.write("	<TD NOWRAP></TD>\n");
      out.write("	<TD NOWRAP WIDTH=\"100%\">\n");
      out.write("		<INPUT TYPE=\"HIDDEN\" ID=\"control_type\" VALUE=\"text\">\n");
      out.write("		<INPUT TYPE=\"HIDDEN\" ID=\"data_type\" VALUE=\"");
      out.print("" + parameterBean.getParameter( ).getDataType( ) );
      out.write("\">\n");
      out.write("		<INPUT CLASS=\"BirtViewer_parameter_dialog_Input\" \n");
      out.write("			category=\"");
      out.print( parameterBean.getParameter().getCategory());
      out.write("\"\n");
      out.write("			pattern=\"");
      out.print( parameterBean.getParameter().getPattern());
      out.write("\"\n");
      out.write("			\n");
      out.write("			");

				if (parameterBean.getParameter().getCategory().equals("Date Picker")					) {
			
      out.write("\n");
      out.write("			TYPE=\"date\"\n");
      out.write("			");

				} else if (		parameterBean.getParameter().getDataType() == ParameterDefinition.TYPE_DATE_TIME
							&&	parameterBean.getParameter().getCategory().startsWith("Date Picker")	) {
			
      out.write("\n");
      out.write("			TYPE=\"datetime-local\"\n");
      out.write("				");
 if (parameterBean.getParameter().getCategory().contains("Medium Time")) { 
      out.write("\n");
      out.write("					step=\"1\"\n");
      out.write("				");
} 
      out.write("\n");
      out.write("			");

				} else if (		parameterBean.getParameter().getDataType() == ParameterDefinition.TYPE_TIME
							&&	parameterBean.getParameter().getCategory().startsWith("Time Picker")	) {
			
      out.write("\n");
      out.write("			TYPE=\"time\"\n");
      out.write("				");
 if (parameterBean.getParameter().getCategory().contains("Medium Time")) { 
      out.write("\n");
      out.write("					step=\"1\"\n");
      out.write("				");
} 
      out.write("\n");
      out.write("			");

				} else if ( parameterBean.isValueConcealed() ) { 
			
      out.write("\n");
      out.write("			TYPE=\"password\" \n");
      out.write("			");

				} else {
			
      out.write("\n");
      out.write("			TYPE=\"text\"\n");
      out.write("			");

				}
			
      out.write("\n");
      out.write("			NAME=\"");
      out.print( encodedParameterName );
      out.write("\"\n");
      out.write("			ID=\"");
      out.print( encodedParameterName );
      out.write("\" \n");
      out.write("			TITLE=\"");
      out.print( parameterBean.getToolTip( ) );
      out.write("\"\n");
      out.write("			VALUE=\"");
      out.print( ParameterAccessor.htmlEncode( ( parameterBean.getDisplayText( ) == null ) ? "" : parameterBean.getDisplayText( ) ) );
      out.write("\" \n");
      out.write("			");
      out.print( ( !parameterBean.isRequired( ) && parameterBean.getValue( ) == null )? "DISABLED='true'" : "" );
      out.write("\n");
      out.write("			");
      out.print( parameterBean.isRequired( ) ? "aria-required='true'" : "" );
      out.write("\n");
      out.write("            >\n");
      out.write("		");

		if ( !parameterBean.isRequired( ) )
		{
		
      out.write("\n");
      out.write("		<INPUT TYPE=\"CHECKBOX\"\n");
      out.write("			ID=\"");
      out.print( encodedParameterName + "_checkbox");
      out.write("\"\n");
      out.write("			VALUE=\"");
      out.print( encodedParameterName );
      out.write("\"\n");
      out.write("			");
      out.print( ( parameterBean.getValue( ) == null )? "CHECKED" : "" );
      out.write("\n");
      out.write("			REQUIRED=true\n");
      out.write("			>\n");
      out.write("		<LABEL FOR=\"");
      out.print( encodedParameterName + "_checkbox");
      out.write("\" CLASS=\"birtviewer_label\">Null Value</LABEL>\n");
      out.write("		");

		}
		
      out.write("\n");
      out.write("\n");
      out.write("		<INPUT TYPE=\"HIDDEN\"\n");
      out.write("			ID=\"");
      out.print( encodedParameterName + "_value" );
      out.write("\"\n");
      out.write("			VALUE=\"");
      out.print( ParameterAccessor.htmlEncode( ( parameterBean.getValue( ) == null )? "" : parameterBean.getValue( ) ) );
      out.write("\"\n");
      out.write("			>		\n");
      out.write("		<INPUT TYPE=\"HIDDEN\"\n");
      out.write("			ID=\"");
      out.print( encodedParameterName + "_displayText" );
      out.write("\"\n");
      out.write("			VALUE=\"");
      out.print( ParameterAccessor.htmlEncode( ( parameterBean.getDisplayText( ) == null )? "" : parameterBean.getDisplayText( ) ) );
      out.write("\"\n");
      out.write("			>\n");
      out.write("		<INPUT TYPE=\"HIDDEN\" ID=\"isRequired\" \n");
      out.write("			VALUE = \"");
      out.print( parameterBean.isRequired( )? "true": "false" );
      out.write("\"\n");
      out.write("			>\n");
      out.write("	</TD>\n");
      out.write("</TR>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
